### ISSUE TITLE
Can this be set up using react?

### ISSUE THREAD

**Issue by mmasdivins** [abartho/electron-typescript-vscode#1]
Hello,
First of all thanks for this example showing how to set up electron debugging with typescript it's really helpful. I have an existing project with electron and typescript using react, the problem I have is that I'm unable to debug the renderer using visual studio code. I've tried setting the launch.json as in your example, but it gives me an error electron: Failed to load the URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED. Should we do something different to set up the debugger with react?
Thanks for your attention!

**Comment by abartho** [comment]
Hello,
I have no experience with React, so I cannot help right now. But if you are able to provide a minimum running example that you can't debug, I'm happy to have a look.
